services:
  adminer:
    depends_on:
      db:
        condition: service_healthy
    image: adminer:latest
    ports:
      - 8080:8080
    restart: on-failure
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: hunt
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    healthcheck:
      interval: 10s
      retries: 10
      test: ["CMD", "pg_isready", "-q", "-d", "lydia_cfonb", "-U", "postgres"]
      timeout: 45s
    image: postgres:15.2
    ports:
      - 5432:5432
    volumes:
      - data01:/var/lib/postgresql/data

version: '3.8'

volumes:
  data01:
    driver: local
